apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: kube-system
  labels:
    app: appd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appd
  template:
    metadata:
      labels:
        app: appd
    spec:
      containers:
      - name: appd
        image: niole/theblog:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: kube-system
spec:
  selector:
    app: appd
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-service
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: blog.niole
    http:
      paths:
      - backend:
          serviceName: app-service
          servicePort: 80
