apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb-edit
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 8080
      name: admin
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: traefik.niole
    http:
      paths:
      - backend:
          serviceName: traefik-web-service
          servicePort: 80
